### ISSUE TITLE
How to build ?

### ISSUE THREAD

**Issue by meskaya** [loouislow81/lyft#1]
Hi @loouislow81,
Is it possible to document the build of your tool ?
I tried to build deb packages but completely failed.
Also can you document the dependencies when building from source ?

Sorry if all of this is already somewhere and I missed it :)

**Comment by loouislow81** [comment]
Besides the complete user manual, I just found out I didn't include any detail on how to build the tool from scratch.

I really need to clean up the documentation one day, but I reply to your answer here.

The tool was written in **Vala** language (another kind of C#). In your Linux (Ubuntu/Debian) you need to install **Vala Compiler**,

```
$ sudo apt install -y valac
```

To compiler from source,

```
$ make
```

The compiled binary is located in `src/` directory.

```
$ ./lyft --help
```

Just that. Enjoy!

**Comment by meskaya** [comment]
Thanks @loouislow81 
I am missing some dependencies to compile from source.
Can you help ?

```
→ make                                                                                                                                                                                        
cd src; make all                                                                                                                                                                                           
make[1]: Entering directory '/home/fraiar01/lyft/src'                                                                                                                                                      
valac -X -D'GETTEXT_PACKAGE="lyft"' --Xcc="-lm" --Xcc="-Os" --thread \                                                                                                                                     
        *.vala Console/*.vala Utility/Console/*.vala \                                                                                                                                                     
        -o lyft \                                                                                                                                                                                          
        --pkg glib-2.0 \                                                                                                                                                                                   
        --pkg gio-unix-2.0 \                                                                                                                                                                               
        --pkg posix \                                                                                                                                                                                      
        --pkg gee-0.8 #--pkg json-glib-1.0                                                                                                                                                                 
Command-line option `--thread` is deprecated and will be ignored                                     
error: Package `glib-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `gobject-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `glib-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `gio-unix-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `posix' not found in specified Vala API directories or GObject-Introspection GIR directories      
error: Package `gee-0.8' not found in specified Vala API directories or GObject-Introspection GIR directories 
Compilation failed: 6 error(s), 0 warning(s)                                                                                                                                                               
make[1]: *** [makefile:20: lyft-console] Error 1                                                                                                                                                           
make: *** [makefile:2: all] Error 2

**Comment by loouislow81** [comment]
@meskaya could you tell me which Linux **distro** and **version** you use? I still using Ubuntu 16.04, the **Valac** has maybe included those dependencies. So I didn't include them in the **Makefile**. Maybe **Valac** on other distro has a different story.

**Comment by meskaya** [comment]
I tried to compile on Ubuntu 20.04

**Comment by loouislow81** [comment]
@meskaya Let me test it on a Docker container (Ubuntu 20.04). I'll include all the necessary dependencies in the `Makefile`. If everything went well.

**Comment by loouislow81** [comment]
I have tested on `Ubuntu 20.04`, the version of `Valac` is a `0.48.6`, but the project was developed using version `0.30.0`. The version `0.30.0` couldn't be installed on `Ubuntu 20.04`. So I made this temporary solution to build from a source inside a Docker container with `Ubuntu 16.04` image.

At somewhere in your host system `Ubuntu 20.04`, we need a new directory,

```bash
$ mkdir lyft-build-env
$ cd lyft-build-env
```
While still in the new `lyft-build-env/` directory, create a new file called `Dockerfile` and include below the docker script. We will be going to build from the source inside the container.

```dockerfile
FROM ubuntu:16.04

RUN apt update; apt upgrade --yes; \
    apt install -y \
      build-essential \
      git cron rsync \
      valac libgee-0.8-2 libgee-0.8-dev

RUN cd /home/
WORKDIR /home/

RUN git clone https://github.com/loouislow81/lyft.git
RUN cd lyft; make clean; make
```
The next step is to build a new Docker container named `lyft-build-env`, which it will appear in the list with the `$ docker images` command. While a new container is building, the Docker script also automatically builds the `Lyft` inside the container. Wait until the build process for the `container` and `binary` are completed (...ignore the warning messages).

```bash
# EXAMPLE (docker build -t {container_name})
(lyft-build-env) $ docker build -t lyft-build-env .
```

Open a new Terminal, we first run the new container `lyft-build-env`, and let it open without doing anything,

```bash
# EXAMPLE (docker run -it {container_name})
$ docker run -it lyft-build-env
```

We are going to copy the `Lyft` binary from the container into your host system (Ubuntu 20.04).

By doing so, copy the `Container ID`, that looks like this,

```bash
# EXAMPLE (e.g. 24e1e26a6859)
$ root@24e1e26a6859:
```

Open another new Terminal again, we are going to copy the binary to your host system,

```bash
# EXAMPLE (docker cp {container_id}:/source_path/ /destination_path/)
$ docker cp 24e1e26a6859:/home/lyft/src/lyft /home/
```

The copied `lyft` binary file is located in your host directory `/home/`. And you can start using it.

Hope this helps.

**Comment by meskaya** [comment]
Thanks @loouislow81 

Compilation in the container worked

```
Compilation succeeded - 7 warning(s)                                                                                                                                                                       
make[1]: Leaving directory '/home/lyft/src'                                                                                                                                                                
Removing intermediate container f0d53f31c615                                                                                                                                                               
 ---> 90caacc662f3                                                                                                                                                                                         
Successfully built 90caacc662f3                                                                                                                                                                            
Successfully tagged lyft-build-env:latest   
 
```
I am getting a seg fault unfortunately :(

```
→ ./lyft
Segmentation fault (core dumped)
